import type { AIChatMessage } from '../../services/ai'

const resumeProfileSchema = [
  '{',
  '  "candidate": {',
  '    "name": "string|null",',
  '    "email": "string|null",',
  '    "phone": "string|null",',
  '    "location": "string|null",',
  '    "links": ["string"]',
  '  },',
  '  "summary": "string|null",',
  '  "totalYearsOfExperience": "number|null",',
  '  "statedTargetRoles": ["string"],',
  '  "technicalSkills": ["string"],',
  '  "softSkills": ["string"],',
  '  "toolsAndPlatforms": ["string"],',
  '  "domainKeywords": ["string"],',
  '  "workExperiences": [',
  '    {',
  '      "company": "string|null",',
  '      "title": "string|null",',
  '      "location": "string|null",',
  '      "startDate": "YYYY-MM|YYYY|present|null",',
  '      "endDate": "YYYY-MM|YYYY|present|null",',
  '      "responsibilities": ["string"],',
  '      "achievements": ["string"],',
  '      "technologies": ["string"]',
  '    }',
  '  ],',
  '  "projects": [',
  '    {',
  '      "name": "string|null",',
  '      "role": "string|null",',
  '      "description": "string|null",',
  '      "responsibilities": ["string"],',
  '      "achievements": ["string"],',
  '      "technologies": ["string"]',
  '    }',
  '  ],',
  '  "education": [',
  '    {',
  '      "school": "string|null",',
  '      "degree": "string|null",',
  '      "major": "string|null",',
  '      "startDate": "YYYY-MM|YYYY|present|null",',
  '      "endDate": "YYYY-MM|YYYY|present|null"',
  '    }',
  '  ],',
  '  "certifications": ["string"],',
  '  "languages": ["string"],',
  '  "achievements": ["string"],',
  '  "uncertainties": ["string"]',
  '}',
].join('\n')

export function buildResumeAgentMessages(resumeText: string): AIChatMessage[] {
  return [
    {
      role: 'system',
      content: [
        'You are the Resume Agent for AI Career Copilot.',
        '',
        'Your task:',
        'Extract factual information from a resume and return structured JSON.',
        '',
        'Rules:',
        '- Only use facts explicitly present in the resume text.',
        '- Do not invent experience, skills, metrics, projects, employers, dates, education, or quantified results.',
        '- Do not optimize the resume.',
        '- Do not give career advice.',
        '- Do not match the resume to any job.',
        '- Only extract statedTargetRoles when the resume explicitly states target roles. Do not infer career direction from experience.',
        '- Calculate totalYearsOfExperience only when dates are clear enough. Do not double-count overlapping work periods. Use null when it cannot be calculated reliably.',
        '- Normalize dates as YYYY-MM, YYYY, present, or null when possible.',
        '- If information is missing, use null or [].',
        '- Use the primary language of the resume for natural-language values.',
        '- Keep technical terms and proper nouns in their original form.',
        '- Return JSON only. No markdown. No explanation.',
        '- Do not output reasoning, analysis, planning, or step-by-step thoughts.',
        '- Do not start with phrases like "We need", "I will", "Here is", or "Analysis".',
        '- The first character of your response must be "{" and the last character must be "}".',
      ].join('\n'),
    },
    {
      role: 'user',
      content: [
        'Analyze this resume text:',
        '',
        '<RESUME>',
        resumeText,
        '</RESUME>',
        '',
        'Return JSON matching this schema:',
        resumeProfileSchema,
      ].join('\n'),
    },
  ]
}

export function buildResumeJsonRepairMessages(resumeText: string): AIChatMessage[] {
  return [
    {
      role: 'system',
      content: [
        'You repair AI output for the Resume Agent.',
        'Return valid JSON only. No markdown. No explanation.',
        'The first character must be "{" and the last character must be "}".',
        'Do not output reasoning, analysis, planning, or step-by-step thoughts.',
        'Do not start with phrases like "We need", "I will", "Here is", or "Analysis".',
        'Use only facts explicitly present in the original resume text.',
        'Use the primary language of the original resume for natural-language values.',
        'Keep technical terms and proper nouns in their original form.',
      ].join('\n'),
    },
    {
      role: 'user',
      content: [
        'The previous response was not parseable as valid JSON because it included non-JSON text.',
        'Ignore the previous response and re-extract the resume facts from the original resume text only.',
        'Return exactly one JSON object matching this schema.',
        '',
        'Schema:',
        resumeProfileSchema,
        '',
        'Original resume text:',
        '<RESUME>',
        resumeText,
        '</RESUME>',
      ].join('\n'),
    },
  ]
}
