import type { AIChatMessage } from '../../services/ai'
import type { JobAnalyzerResult, ResumeProfile } from '..'

const jobMatchSchema = [
  '{',
  '  "overallScore": 0,',
  '  "recommendation": "strong_apply|apply|consider|not_recommended",',
  '  "summary": "string",',
  '  "scoreBreakdown": {',
  '    "technicalFit": 0,',
  '    "experienceFit": 0,',
  '    "domainFit": 0,',
  '    "projectFit": 0,',
  '    "requirementFit": 0',
  '  },',
  '  "matchedStrengths": [{"requirement": "string", "evidenceFromResume": "string", "explanation": "string"}],',
  '  "partialMatches": [{"requirement": "string", "evidenceFromResume": "string", "explanation": "string"}],',
  '  "gaps": [{"requirement": "string", "gapType": "missing|weak|unclear", "explanation": "string", "severity": "low|medium|high"}],',
  '  "blockingGaps": [{"requirement": "string", "reason": "string", "severity": "medium|high", "canBeMitigatedByTransferableStrength": false}],',
  '  "transferableStrengths": [{"fromResume": "string", "appliesToRequirement": "string", "transferReason": "string", "confidence": "low|medium|high"}],',
  '  "risks": [{"risk": "string", "reason": "string", "severity": "low|medium|high"}],',
  '  "mustHaveAssessment": [{"requirement": "string", "status": "met|partially_met|not_met|unclear", "evidenceFromResume": "string|null", "explanation": "string"}],',
  '  "niceToHaveAssessment": [{"requirement": "string", "status": "met|partially_met|not_met|unclear", "evidenceFromResume": "string|null", "explanation": "string"}],',
  '  "uncertainties": ["string"]',
  '}',
].join('\n')

export function buildMatchingAgentMessages(
  resumeProfile: ResumeProfile,
  jobAnalysis: JobAnalyzerResult,
): AIChatMessage[] {
  return [
    {
      role: 'system',
      content: [
        'You are the Matching Agent for AI Career Copilot.',
        '',
        'Your task:',
        'Compare a structured ResumeProfile with a structured JobAnalyzerResult and return a structured job match result.',
        '',
        'Rules:',
        '- Only use the provided ResumeProfile and JobAnalyzerResult.',
        '- Do not read or infer from original resume text.',
        '- Do not read or infer from original job description text.',
        '- Do not invent experience, skills, projects, or job requirements.',
        '- Do not generate resume optimization advice.',
        '- Do not generate interview questions.',
        '- Do not give career planning advice.',
        '- Support transferable skill reasoning.',
        '- Do not rely on keyword matching only.',
        '- Distinguish direct matches, partial matches, gaps, blockingGaps, transferable strengths, and risks.',
        '- Identify blockingGaps only for explicit must-have or hard constraints that cannot be reasonably mitigated by transferable strengths.',
        '- Do not treat missing resume information as not qualified. Use unclear when evidence is missing.',
        '- If work authorization, location, remote preference, language, education, or certification evidence is missing from the resume, default to unclear rather than not_met.',
        '- Missing information alone is not a blockingGap. Use blockingGaps only when there is explicit contradictory evidence or an explicit must-have cannot be reasonably satisfied by the resume evidence.',
        '- If a must-have assessment status is unclear, do not include that requirement in blockingGaps.',
        '- Only not_met must-have assessments can become blockingGaps.',
        '- Work history in another country does not prove the candidate cannot relocate or work onsite. Without explicit evidence, treat location/onsite/work authorization as unclear.',
        '- Explicit certification requirements cannot be satisfied by adjacent technical experience. If a required certification is absent from ResumeProfile certifications and skills, mark it not_met and consider it a blockingGap.',
        '- Must-have requirements include technical requirements, location or remote constraints, work authorization, language, education, certifications, explicit years of experience, and other hard constraints.',
        '- Vue to React and adjacent technology stacks should usually be partialMatches or transferableStrengths, not blockingGaps, unless the JD explicitly requires non-transferable deep experience and the resume has no adjacent evidence.',
        '- Nice-to-have gaps must not become blockingGaps.',
        '- Return JSON only. No markdown. No explanation.',
        '- Do not output reasoning, analysis, planning, or step-by-step thoughts.',
        '- The first character of your response must be "{" and the last character must be "}".',
      ].join('\n'),
    },
    {
      role: 'user',
      content: [
        'ResumeProfile:',
        JSON.stringify(resumeProfile, null, 2),
        '',
        'JobAnalyzerResult:',
        JSON.stringify(jobAnalysis, null, 2),
        '',
        'Use this scoring formula:',
        'technicalFit 30%',
        'experienceFit 20%',
        'domainFit 15%',
        'projectFit 15%',
        'requirementFit 20%',
        '',
        'Important scoring instruction:',
        'Each scoreBreakdown field must be a raw 0-100 dimension score, not weighted contribution points.',
        'For example, if technicalFit is excellent, return technicalFit around 85-100, not 25-30.',
        'The app will apply the weights locally.',
        '',
        'Requirement fit is based mainly on must-have requirements. Nice-to-have requirements should have only a small influence.',
        'Recommendation must be determined by both overallScore and blockingGaps.',
        'If any high severity blockingGap exists, recommendation cannot be higher than consider.',
        'If any medium severity blockingGap exists, recommendation cannot be higher than apply.',
        'The app will recalculate overallScore and recommendation locally, but you must still provide scoreBreakdown and evidence.',
        '',
        'Return JSON matching this schema:',
        jobMatchSchema,
      ].join('\n'),
    },
  ]
}

export function buildMatchingJsonRepairMessages(
  resumeProfile: ResumeProfile,
  jobAnalysis: JobAnalyzerResult,
): AIChatMessage[] {
  return [
    {
      role: 'system',
      content: [
        'You repair AI output for the Matching Agent.',
        'Return valid JSON only. No markdown. No explanation.',
        'Do not output reasoning, analysis, planning, or step-by-step thoughts.',
        'The first character must be "{" and the last character must be "}".',
        'Only use the provided ResumeProfile and JobAnalyzerResult.',
        'Keep missing evidence as unclear instead of assuming not qualified.',
      ].join('\n'),
    },
    {
      role: 'user',
      content: [
        'Generate a valid JSON job match result from these structured inputs.',
        '',
        'ResumeProfile:',
        JSON.stringify(resumeProfile, null, 2),
        '',
        'JobAnalyzerResult:',
        JSON.stringify(jobAnalysis, null, 2),
        '',
        'Schema:',
        jobMatchSchema,
      ].join('\n'),
    },
  ]
}
